# This data file is applied to instances classified with the puppet_server role
# in the production tier of your environment. This is the default for puppet
# masters deployed using the rap-terraform-puppetserver module.

---
classes:
  - role::puppet_server

hiera::hiera_version: '5'
hiera::hiera5_defaults: {'datadir': '/etc/puppetlabs/code/hiera', 'data_hash': 'yaml_data'}
hiera::hierarchy:
  - name: Eyaml backend
    lookup_key: 'eyaml_lookup_key'
    paths:
      - "%%{%}{::environment}/instance_classification/%%{%}{::instance_tier}/applications/%%{%}{::instance_application}.yaml"
      - "%%{%}{::environment}/instance_classification/%%{%}{::instance_tier}/roles/%%{%}{::instance_role}.yaml"
      - "%%{%}{::environment}/instance_classification/%%{%}{::instance_tier}/common.yaml"
      - "%%{%}{::environment}/common.yaml"
    datadir: "/etc/puppetlabs/code/hiera"
    options:
      extension: yaml
      pkcs7_private_key: "/etc/puppetlabs/puppet/keys/private_key.pkcs7.pem"
      pkcs7_public_key: "/etc/puppetlabs/puppet/keys/public_key.pkcs7.pem"
  - name: Yaml backend
    data_hash: yaml_data
    paths:
      - "%%{%}{::environment}/instance_classification/%%{%}{::instance_tier}/applications/%%{%}{::instance_application}.yaml"
      - "%%{%}{::environment}/instance_classification/%%{%}{::instance_tier}/roles/%%{%}{::instance_role}.yaml"
      - "%%{%}{::environment}/instance_classification/%%{%}{::instance_tier}/common.yaml"
      - "%%{%}{::environment}/common.yaml"
    datadir: "/etc/puppetlabs/code/hiera"

hiera::master_service: 'puppetserver'
hiera::provider: 'puppetserver_gem'
hiera::hiera_yaml: '/etc/puppetlabs/code/hiera.yaml'
hiera::puppet_conf_manage: false
hiera::datadir_manage: false
hiera::eyaml_extension: 'yaml'
hiera::eyaml_version: '3.2.0'
hiera::eyaml: true
